# Generated by Django 2.2.19 on 2022-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование ингридиента')),
                ('unit', models.CharField(max_length=200, verbose_name='Единица измерения')),
            ],
        ),
    ]
